#!/usr/bin/perl
# $File: //member/autrijus/PAR/lib/PAR.pm $ $Author: autrijus $
# $Revision: #58 $ $Change: 9671 $ $DateTime: 2004/01/11 14:33:54 $ vim: expandtab shiftwidth=4

use App::Packer::Temp;
use App::Packer::Backend::PAR;;
use Getopt::Long qw(:config no_ignore_case);

my $opt = {};
GetOptions( $opt, App::Packer::Backend::PAR->options );

App::Packer::Temp->new(
    frontend    => 'Module::ScanDeps',
    backend     => 'App::Packer::Backend::PAR',
    frontopts   => $opt,
    backopts    => $opt,
    args        => \@ARGV,
)->go;

