---
abstract: 'Perl Archive Tookit'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PAR
no_index:
  directory:
    - inc
    - t
provides:
  PAR:
    file: lib/PAR.pm
    version: 0.986
  PAR::Heavy:
    file: lib/PAR/Heavy.pm
    version: 0.11
  PAR::SetupProgname:
    file: lib/PAR/SetupProgname.pm
  PAR::SetupTemp:
    file: lib/PAR/SetupTemp.pm
recommends:
  Digest: Module::Signature
requires:
  Archive::Zip: 1
  AutoLoader: 5.66_02
  Compress::Zlib: 1.3
  File::Temp: 0.05
  PAR::Dist: 0.32
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.986
