name: PAR
version: 0.76_99
abstract: Perl Archive Tookit
license: perl
distribution_type: module
requires:
  File::Temp: 0
  Compress::Zlib: 1.3
  Archive::Zip: 1
  Module::ScanDeps: 0.32
  PAR::Dist: 0.05
recommends:
  Digest::SHA1: 0
  Module::Signature: 0.35
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.30
