name: PAR
version: 0.80_99
abstract: Perl Archive Tookit
author: Autrijus Tang (autrijus@autrijus.org)
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  File::Temp: 0.05
  Compress::Zlib: 1.3
  Archive::Zip: 1
  Module::ScanDeps: 0.37
  PAR::Dist: 0.06
recommends:
  Digest::SHA1: 0
  Module::Signature: 0.35
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.32
