--- 
abstract: Perl Archive Tookit
author: 
  - Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PAR
no_index: 
  directory: 
    - contrib
    - inc
    - t
provides: 
  PAR: 
    file: lib/PAR.pm
    version: 0.977
  PAR::Heavy: 
    file: lib/PAR/Heavy.pm
    version: 0.11
recommends: 
  Digest: Module::Signature
requires: 
  Archive::Zip: 1
  AutoLoader: 5.63
  Compress::Zlib: 1.3
  File::Temp: 0.05
  PAR::Dist: 0.22
  perl: 5.6.0
version: 0.977
