abstract: Perl Archive Tookit
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
name: PAR
no_index: 
  directory: 
    - contrib
    - inc
    - t
provides: 
  AutoLoader: 
    file: lib/PAR/AutoLoaderFix.pm
    version: 5.61
  PAR: 
    file: lib/PAR.pm
    version: 0.970_01
  PAR::Heavy: 
    file: lib/PAR/Heavy.pm
    version: 0.09
recommends: 
  Digest: Module::Signature
requires: 
  Archive::Zip: 1
  Compress::Zlib: 1.3
  File::Temp: 0.05
  PAR::Dist: 0.21
  perl: 5.6.0
version: 0.970_01
