abstract: Perl Archive Tookit
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: PAR
no_index: 
  directory: 
    - contrib
    - inc
    - t
recommends: 
  Digest: Module::Signature
requires: 
  Archive::Zip: 1
  Compress::Zlib: 1.3
  File::Temp: 0.05
  Getopt::ArgvFile: 1.07
  Module::ScanDeps: 0.62
  PAR::Dist: 0.13
  perl: 5.6.0
version: 0.942
