---
abstract: 'Perl Archive Tookit'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.6302
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PAR
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Zip: 1
  AutoLoader: 5.66_02
  Compress::Zlib: 1.3
  File::Temp: 0.05
  PAR::Dist: 0.32
  perl: 5.008001
version: 1.006
