name: PAR
version: 0.66
abstract: Perl Archive Tookit
distribution_type: module
requires:
  File::Temp: 0
  Compress::Zlib: 1.14
  Archive::Zip: 1
  Module::ScanDeps: 0.17
generated_by: Module::Install version 0.20
